sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t kylef26/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kylef26/react-test npm test

after_success:
  - docker build -t kylef26/multi-client ./client
  - docker build -t kylef26/multi-server ./server
  - docker build -t kylef26/multi-worker ./worker
  - docker build -t kylef26/multi-nginx ./nginx

  #Log In to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push to Docker Hub
  - docker push kylef26/multi-client
  - docker push kylef26/multi-server
  - docker push kylef26/multi-worker
  - docker push kylef26/multi-nginx